---
title: "Week8"
author: "Benjamin Moran"
date: "13 September 2016"
output: pdf_document
---

###Questions which review material from Week 6:

1. Consider the operator $T \in \mathcal{L}(\mathbb{C}^{4})$, whose matrix representation with respect to the standard basis $\mathcal{B}$ of $\mathbb{C}^{4}$ is:
  $$
    M(T,\mathcal{B}) =
      \begin{pmatrix}
        2 & 0 & 1 & 2 \\
        0 & 3 & 3 & 4 \\
        0 & 0 & 2 & 0 \\
        0 & 0 & 0 & 3
      \end{pmatrix}
  $$
  
    Define the vectors $v_{1} = (1, 0, 0, 0), v_{2} = (0, -3, 1, 0), v_{3} = (0, 2, 0, 0) \text{ and } v_{4} = (2, 0, 0, 1)$, and form the subspaces $U_{1} = \text{span}(v_{1}, v_{2}) \text{ and }U_{2} = span(v_{3}, v_{4})$. Let $\lambda_{1} = 2$ and $\lambda_{2} = 3$.

(a)	Show that $v_{1}$ and $v_{2}$ are generalised eigenvectors corresponding to the eigenvalue $\lambda_{1}$. Show that $v_{3}$ and $v_{4}$ are generalised eigenvectors corresponding to the eigenvalue $\lambda_{2}$.

**Answer:** First, let's find $(M - \lambda I)$ for each eigenvalue and then solve for the corresponding eigenvector. For $\lambda_{1} = 2$, we get:
  $$
    (M - 2I) =
      \begin{pmatrix}
        0 & 0 & 1 & 2 \\
        0 & 1 & 3 & 4 \\
        0 & 0 & 0 & 0 \\
        0 & 0 & 0 & 1
      \end{pmatrix}
  $$
  We can row-reduce this to:
  $$
    \begin{pmatrix}
      0 & 1 & 0 & 0 \\
      0 & 0 & 1 & 0 \\
      0 & 0 & 0 & 1 \\
      0 & 0 & 0 & 0
    \end{pmatrix}
  $$
  which implies that $x_{2} = x_{3} = x_{4} = 0$ Therefore, the eigenvector corresponding to $\lambda_{1}=2$ is $(1, 0, 0, 0) = v_{1}$
  
  For $\lambda_{2} = 3$, we get:
  $$
    (M - 3I) =
      \begin{pmatrix}
        -1 & 0 & 1 & 2 \\
        0 & 0 & 3 & 4 \\
        0 & 0 & -1 & 0 \\
        0 & 0 & 0 & 0
      \end{pmatrix}
  $$
  We can row-reduce this to:
  $$
    \begin{pmatrix}
      1 & 0 & 0 & 0 \\
      0 & 0 & 1 & 0 \\
      0 & 0 & 0 & 1 \\
      0 & 0 & 0 & 0
    \end{pmatrix}
  $$
  which implies that $x_{1} = x_{3} = x_{4} = 0$ Therefore, the eigenvector corresponding to $\lambda_{2}=3$ is $(0, 1, 0, 0) = \frac{1}{2}v_{3}$
  
  Next, let's calculate the generalised eigenvector for $\lambda_{1}=2$. We can do this by solving:
  $$
    \begin{pmatrix}
      0 & 0 & 1 & 2 \\
      0 & 1 & 3 & 4 \\
      0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 1
    \end{pmatrix}
    \begin{pmatrix}
      x_{1} \\
      x_{2} \\
      x_{3} \\
      x_{4}
    \end{pmatrix}
    =
    \begin{pmatrix}
      1 \\
      0 \\
      0 \\
      0
    \end{pmatrix}
  $$
  This system of equations shows that $x_{4} = 0 \implies x_{3} = 1 \implies x_{2} = -3x_{3} = -3$. Therefore, the generalised eigenvector for $\lambda_{1}=2$ is $(0, -3, 1, 0) = v_{2}$
  Repeating the process for $\lambda_{2} = 3$, we get:
  $$
    \begin{pmatrix}
      -1 & 0 & 1 & 2 \\
      0 & 0 & 3 & 4 \\
      0 & 0 & -1 & 0 \\
      0 & 0 & 0 & 0
    \end{pmatrix}
    \begin{pmatrix}
      x_{1} \\
      x_{2} \\
      x_{3} \\
      x_{4}
    \end{pmatrix}
    =
    \begin{pmatrix}
      0 \\
      2 \\
      0 \\
      0
    \end{pmatrix}
  $$
  This system of equations shows that $x_{3} = 0 \implies 4x_{4} = 2 \implies x_{4} = \frac{1}{2} \implies x_{1} = 2x_{2} = 1$. Therefore, the generalised eigenvector for $\lambda_{2}=3$ is $(1, 0, 0, \frac{1}{2}) = \frac{1}{2}v_{4}$.

(b)	Show that $\mathcal{B}' = (v_{1}, v_{2}, v_{3}, v_{4})$ is a basis of $\mathbb{C}^{4}$ consisting of generalised eigenvectors of $T$ .

**Answer:** We define:
  $$
    \begin{aligned}
    M(\mathcal{B}') &=
      \begin{pmatrix}
        1 & 0 & 0 & 2 \\
        0 & -3 & 2 & 0 \\
        0 & 1 & 0 & 0 \\
        0 & 0 & 0 & 1
      \end{pmatrix}
      \xrightarrow{R^*_3 = R_3 + 1/3*R_2} 
      \begin{pmatrix}
        1 & 0 & 0 & 2 \\
        0 & -3 & 1 & 0 \\
        0 & 0 & 2/3 & 1 \\
        0 & 0 & 0 & 1
      \end{pmatrix}
      \xrightarrow{R^*_1 = R_1 - 2*R_2}
      \begin{pmatrix}
        1 & 0 & 0 & 0 \\
        0 & -3 & 1 & 0 \\
        0 & 0 & 2/3 & 1 \\
        0 & 0 & 0 & 1
      \end{pmatrix} \\
      &\implies
      \xrightarrow{R^*_3 = R_3 - R_4}
      \begin{pmatrix}
        1 & 0 & 0 & 0 \\
        0 & -3 & 1 & 0 \\
        0 & 0 & 2/3 & 0 \\
        0 & 0 & 0 & 1
      \end{pmatrix}
      \xrightarrow{R^*_2 = R_2 - 3/2 R_3}
      \begin{pmatrix}
        1 & 0 & 0 & 0 \\
        0 & -3 & 0 & 0 \\
        0 & 0 & 2/3 & 0 \\
        0 & 0 & 0 & 1
      \end{pmatrix}
  \end{aligned}
  $$
  From here, we can easily reduce to the standard basis of $\mathbb{C}^{4}$. Therefore, $\mathcal{B}'$ is a basis of $\mathbb{C}^{4}$.

(c)	Calculate the matrix representation of $T$ with respect to the basis $\mathcal{B}'$ .

**Answer:**   
  $$
    \begin{aligned}
      Tv_{1} &= T(1,0,0,0) = (2,0,0,0) = 2v_{1} \\
      Tv_{2} &= T(0,-3,1,0) = (1,-6,1,0) = v_{1} + v_{3} -3/2\,v_{2} \\
      Tv_{3} &= T(0,2,0,0) = (0,6,0,0) = 3v_{3} \\
      Tv_{4} &= T(2,0,0,1) = (5,4,0,3) = 2v_{3} + 3v_{4} - v_{1} \\
    \end{aligned}
  $$
Therefore, 
  $$
    M(T,\mathcal{B}') =
      \begin{pmatrix}
        2 & 1 & 0 & -1 \\
        0 & -3/2 & 0 & 0 \\
        0 & 1 &3 & 2 \\
        0 & 0 & 0 & 3
      \end{pmatrix}
      \xrightarrow{R^*_3 = R_3 + 2/3 R_2}
      \begin{pmatrix}
        2 & 1 & 0 & -1 \\
        0 & -3/2 & 0 & 0 \\
        0 & 0 &3 & 2 \\
        0 & 0 & 0 & 3
      \end{pmatrix}
      \xrightarrow{R^*_1 = R_1 + 1/3 R_4}
      \begin{pmatrix}
        2 & 1 & 0 & 0 \\
        0 & -3/2 & 0 & 0 \\
        0 & 0 & 3 & 2 \\
        0 & 0 & 0 & 3
      \end{pmatrix}
  $$
2.	Let $T \in \mathcal{L}(\mathbb{C}^{4})$ be the operator from Question 1, and define the same vectors, subspaces and bases as before.

(a)	The matrix representation of $T$ with respect to the basis $\mathcal{B}'$ that you calculated in Question 1(c) should be a block diagonal matrix of the form

  $$
    M(T,\mathcal{B}') =
      \begin{pmatrix}
        A_{1} & 0 \\
        0 & A_{2}
      \end{pmatrix}
  $$
where the block matrices $A_{1}$ and $A_{2}$ are upper-triangular. State $A_{1}$ and $A_{2}$.

**Answer:** We have:
  $$
  \begin{aligned}
    A_{1} 
      &=
      \begin{pmatrix}
        2 & 1 \\
        0 & -3/2
      \end{pmatrix} \\
    A_{2}
      &=
      \begin{pmatrix}
        3 & 2 \\
        0 & 3
      \end{pmatrix} \\
  \end{aligned}
  $$

(b)	The block matrix $A_{1}$ corresponds to the matrix representation of the operator $T\mid_{U_{1}}$ with respect to the basis $(v_{1}, v_{2})$ of $U_{1}$. Similarly, the block matrix $A_{2}$ corresponds to the matrix representation of the operator $T\mid_{U_{2}}$ with respect to the basis $(v_{3}, v_{4})$ of $U_{2}$.    
Define the operators $N_{1}$ and $N_{2}$ to be $(T - \lambda_{1} I)\mid_{U_{1}}$ and $(T - \lambda_{2} I)\mid_{U_{2}}$ respectively. Write down the matrix representation of $N_{1}$ with respect to the basis $(v_{1}, v_{2})$ of $U_{1}$, and the matrix representation of $N_{2}$ with respect to the basis $(v_{3}, v_{4})$ of $U_{2}$.

**Answer:** We have:
  $$
  \begin{aligned}
    N_{1} = (T-2I)\mid_{U_{1}}
      &=
      \begin{pmatrix}
        0 & 1 \\
        0 & -7/2
      \end{pmatrix} 
      \xrightarrow{R^*_2 = R_2 + 7/2 R_1}
      \begin{pmatrix}
        0 & 1 \\
        0 & 0
      \end{pmatrix} \\
    N_{2} = (T-3I)\mid_{U_{2}}
      &=
      \begin{pmatrix}
        0 & 2 \\
        0 & 0
      \end{pmatrix} \\
  \end{aligned}
  $$


(c)	Verify that the operators $N_{1}$ and $N_{2}$ are nilpotent.

  **Answer:** It is easy to see that:
  $$
    N_{1}^{2} 
    =
    N_{2}^{2} 
    =
     \begin{pmatrix}
       0 & 0 \\
       0 & 0
      \end{pmatrix}
  $$
  Therefore, $N_{1}$ and $N_{2}$ are nilpotent.

###Introductory level question relating to Week 7:

3. Let $a, b, c \in \mathbb{C}$ be nonzero scalars with $a \neq b.$ Consider the operator $T \in \mathcal{L}(\mathbb{C}^{5})$, whose matrix representation with respect to some basis of $\mathbb{C}^{5}$ is:
  $$
    M(T) =
      \begin{pmatrix}
        a & 0 & 0 & 0 & 0 \\
        0 & a & 0 & 0 & 0 \\
        0 & 0 & a & 0 & 0 \\
        0 & 0 & 0 & b & c \\
        0 & 0 & 0 & 0 & b
      \end{pmatrix}
  $$

(a)	What is the characteristic polynomial, $q(z)$, of the operator $T$?

**Answer:** Because this matrix is upper-triangular, we can basically read the characteristic polynomial off of the main diagonal. In this case $q(z) = (a-z)^{3}(b-z)^{2}$.

(b)	List all the monic polynomials (of degree at least 1) that divide $q(z)$.

**Answer:** $(a-z)^{3}, (a-z)^{2}, (a-z), (b-z)^{2}$ and $(b-z)$ are all monic polynomials that divide $q(z)$. So are $(a-z)^{3}(b-z), (a-z)^{3}(b-z)^{2}, (a-z)^{2}(b-z)^{2}, (a-z)(b-z)$ and $(a-z)(b-z)^{2}$.

(c)	Which of your polynomials from (b) have roots at each distinct eigenvalue of $T$?

**Answer:** $(a-z)^{3},(a-z)^{2},(a-z)$ and $(a-z)^{3}(b-z), (a-z)^{2}(b-z),(a-z)^{2}(b-z)^{2}, (a-z)(b-z)$ all have a root at $\lambda_{1} = a$. $(b-z)^{2}, (b-z)$; $(a-z)^{3}(b-z), (a-z)^{2}(b-z), (a-z)^{2}(b-z)^{2}, (a-z)(b-z)$ and $(b-z)^{2}, (b-z)$ all have a root at $\lambda_{2} = b$.

(d)	Hence determine the minimal polynomial, $p(z)$, of the operator $T$ by showing $p(T) = 0$.

**Answer:** The minimimal polynomial is therefore $p(z) = (a-z)(b-z)$.


###Submitting your assignment (due 5pm Tuesday 13th September 2016)

*Submit your assignment in hardcopy in your Demonstrator's pigeonhole in the Assignment boxes near the Maths Clinic, on the opposite wall to the Maths Clinic, left of the door to v09. We also ask that you scan your written work and submit it on the MATH2320 UoNline/Blackboard site as a backup and proof of submission, not as a substitute. __Note that we still require the hardcopy submitted in the Assignment Box for your Demonstrator to mark, even if you have submitted a backup on Blackboard.__*


