---
title: "Week5"
author: "B. Moran"
date: "26 August 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```
**Due:** 5pm Tuesday 30th August 2016.

If you have any questions about this assignment, please see or email your lecturer for this course, Dr Daniel Sutherland <Daniel.Sutherland@newcastle.edu.au>.

***

###Questions which review material from Week 4:

####1. Consider the operator $T\in \mathcal{L}(\mathcal{P}_{2}(\mathbb{R}))$ defined by

$$T (p(x)) = p(x) + xp'(x):$$

(a)	Find $null\>T$ and use this to conclude that $T$ must be invertible.

**Answer:**

First, let's determine the effect of $T(p(x)): \forall p(x) \in \mathcal{P}_{2}(\mathbb{R})$. Define a polynomial $p_1(x) := a + bx + cx^2, a,b,c \in \mathbb{R}$. Then we have.

$$\begin{aligned} T(p_{1}(x)) &= T(a + bx + cx^2) \\
&= a + bx + cx^2 + x(b + 2cx) \\
&=a + 2bx + 3cx^2.
\end{aligned}$$

Let's rewrite $T$ in the form $A\vec{x}$, where $A$ is a matrix and $\vec{x}$ is a vector. We get.

$$\begin{bmatrix}1 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 3 \end{bmatrix} \begin{bmatrix}a \\ bx \\ cx^2 \end{bmatrix} = \begin{bmatrix} a \\ 2bx \\ 3cx^2 \end{bmatrix}$$

A vector $\vec{x}$ in the null space of $A$ will satisfy the equation $A\vec{x} = \vec{0}$. It is clear that the only coefficients $a,b,c$ that satisfy this requirement for the operator $T$ are $0$. Therefore, $\vec{x}=\vec{0}$, which implies that $T$ is invertible.

(b)	Define the one-dimensional subspaces

$$U_{1} = \left\{a1 : a \in \mathbb{R}\right\},	U_{2} = \left\{bx : bx \in \mathbb{R}\right\}\>	\text{and}\>	U_{3} = \left\{cx^{2} : c \in \mathbb{R}\right\}:$$

Show that each of the above subspaces are invariant under $T$.

**Answer:** Here we get:

$$\begin{aligned} T(a1) &= T(a1 + 0 + 0) \\
&= a1 + 0 + 0 + x(0 + 0) \\
&=a1. \\
T(bx) &= T(0 + bx + 0) \\
&= 0 + bx + 0 + x(b + 0) \\
&=2bx. \\
T(cx^2) &= T(0 + 0 + cx^2) \\
&= 0 + 0 + cx^2 + x(0 + 2cx) \\
&=3cx^2.
\end{aligned}$$

The operator $T$ when acting on $U_{1,2,3}$ returns a scalar multiple of $U_{1,2,3}$. Therefore, these sub-spaces are invariant under $T$.

(c) Hence, what are the eigenvalues of $T$? How can you be sure that there are no more?

**Answer:** The eigen values of $T$ are: $\lambda = 1$, with corresponding eigenvector $(1,0,0)$; $\lambda = 2$, with corresponding eigenvector $(0,1,0)$; and $\lambda = 3$, with corresponding eigenvector $(0,0,1)$.

We know there aren't any more because the number of distinct eigenvalues for an operator cannot be greater than the dimension of that operator.

***

2. Consider the operator $S \in \mathcal{L}(\mathcal{P}_{2}(\mathbb{R}))$ defined by
$$S(p(x)) = x^{-1}\int\limits_{0}^{x}p(t)dt.$$

(a)	Show that each subspace $U_{1}$, $U_{2}$ and $U_{3}$ (from Question 1) is invariant under $S$.

**Answer:**
Here we get:

$$\begin{aligned} S(a1) &= S(a1 + 0 + 0) \\
&= x^{-1}(ax + 0 + 0) \\
&=a1. \\
S(bx) &= S(0 + bx + 0) \\
&= x^{-1}(0 + \frac{bx^2}{2} + 0) \\
&=\frac{bx}{2}. \\
S(cx^2) &= S(0 + 0 + cx^2) \\
&= x^{-1}(0+ 0 + \frac{cx^3}{3}) \\
&=\frac{cx^2}{3}.
\end{aligned}$$

The operator $S$ when acting on $U_{1,2,3}$ returns a scalar multiple of $U_{1,2,3}$. Therefore, these sub-spaces are invariant under $S$.

(b)	Hence, what are the eigenvalues of $S$? How can you be sure that there are no more? 

The eigen values of $S$ are: $\lambda = 1$, with corresponding eigenvector $(1,0,0)$; $\lambda = \frac{1}{2}$, with corresponding eigenvector $(0,1,0)$; and $\lambda = \frac{1}{3}$, with corresponding eigenvector $(0,0,1)$.

We know there aren't any more because the number of distinct eigenvalues for an operator cannot be greater than the dimension of that operator.

(c)	By calculating $S(T (a + bx + cx^{2}))$ and $T(S(a + bx + cx^{2}))$, conclude that $T^{-1} = S$.

**Answer:** 
$$\begin{aligned} S(T(a + bx + cx^{2})) &= S(a + 2bx + 3cx^2) \\
&= x^{-1}(ax + \frac{2bx^2}{2} + \frac{3cx^3}{3}) \\
&=a + bx + cx^2.\\
T(S(a + bx + cx^{2})) &= T(a + \frac{bx}{2} + \frac{cx^2}{3}) \\
&= a + \frac{bx}{2} + \frac{cx^2}{3} + x(0 + \frac{b}{2} + \frac{2cx}{3}) \\
&=a + bx + cx^2.\\
\end{aligned}$$

***
###Introductory level question relating to Week 5:

3. Consider the operator$T\in \mathcal{L}(\mathbb{R}3)$ defined by

$$T (x, y, z) = (2x + z, x + y + z, x + 2z):$$

(a)	Show that the basis $B = ((1, 0, 1), (1, 1, 1), (0, 1, 0))$ of $\mathbb{R}^3$ consists of eigenvectors of $T$. To what eigenvalue does each eigenvector correspond?

**Answer:** The matrix representation of $T$ is:

$$A = \begin{bmatrix}2 & 0 & 1 \\ 1 & 1 & 1 \\ 1 & 0 & 2 \end{bmatrix}$$

Next, find $det(A-\lambda I)$.
$$\begin{aligned} det(A-\lambda I) &= det\left(\begin{bmatrix}2 & 0 & 1 \\ 1 & 1 & 1 \\ 1 & 0 & 2 \end{bmatrix} - \begin{bmatrix}\lambda & 0 & 0 \\ 0 & \lambda & 0 \\ 0 & 0 & \lambda \end{bmatrix}\right) \\
&= det\left(\begin{bmatrix}(2-\lambda) & 0 & 1 \\ 1 & (1-\lambda) & 1 \\ 1 & 0 & (2-\lambda) \end{bmatrix}\right) \\
&=(\lambda - 3)(\lambda -1)^{2}
\end{aligned}$$

So we have one eigenvalue $\lambda = 3$ with a multiplicity of $1$ and another eigenvalue $\lambda = 1$ with a multiplicity of $2$. Now we solve for the corresponding eigenvectors. Firstly, $\lambda = 3$.
$$\begin{aligned} (A-3I)\vec{x} &= \begin{bmatrix}-1 & 0 & 1 \\ 1 & -2 & 1 \\ 1 & 0 & -1 \end{bmatrix} \begin{bmatrix} x \\ y \\ z \end{bmatrix} \\
&= \begin{bmatrix} -x + z \\ x -2y + z \\ x - z \end{bmatrix}
\end{aligned}$$
Now we solve the system of equations:
$$\begin{aligned} -x + z &= 0 \implies &x = z \\
x - 2y + z &= 0 \\
2y &= x + z \implies &y = x = z
\end{aligned}$$
which means the corresponding eigenvector is $(1,1,1)$ for $\lambda = 3$. 

Next, $\lambda = 1$
$$\begin{aligned} (A-1I)\vec{x} &= \begin{bmatrix}1 & 0 & 1 \\ 1 & 0 & 1 \\ 1 & 0 & 1 \end{bmatrix} \begin{bmatrix} x \\ y \\ z \end{bmatrix} \\
&= \begin{bmatrix} x + z \\ x + z \\ x + z \end{bmatrix}
\end{aligned}$$

From these equations we will get two eigenvectors, because of the multiplicity of the eigenvalue:

$$\begin{aligned} x + z &= 0 \implies &x = -z \\
y &= 0
\end{aligned}$$

which leaves us with corresponding eigenvectors $(1, 0 , -1)$ and $(0, 1, 0)$ for $\lambda = 1$. Thus, $B$ consists of eigenvectors of $T$.

(b)	Recall the following result from the textbook:

> Proposition 5.20: If $T\in \mathcal{L}(V)$ has $dim \> V$ distinct eigenvalues, then $T$ has a diagonal matrix with respect to some basis of $V$.

Does this result, together with your observations from part (a), allow you to conclude anything?

**Answer:** We can conclude that $T$ **does not** have a diagonal matrix with respect to the basis $B$ because it does not have $dim \> \mathbb{R}^{3} = 3$ *distinct* eigenvectors: it has two, $\lambda = 3$ and $\lambda = 1$.

***

###Extension question - will not be marked, just for interest!

4. Consider the operator$T\in \mathcal{L}(P2(\mathbb{R}))$ defined by

$$T (p(x)) = p(x) + 3xp'(x) + x^{2}p''(x).$$

Show that $T$ is invertible by calculating $null\>T$.

By modifying Questions 1 and 2, can you determine an explicit formula for the inverse of $T$?


#####Submitting your assignment (due 5pm Tuesday 30th August 2016)

*Submit your assignment in hardcopy in your Demonstrator's pigeonhole in the Assignment boxes near the Maths Clinic, on the opposite wall to the Maths Clinic, left of the door to V109. We also ask that you scan your written work and submit it on the MATH2320 UoNline/Blackboard site as a backup and proof of submission, not as a substitute. __Note that we still require the hardcopy submitted in the Assignment Box for your Demonstrator to mark, even if you have submitted a backup on Blackboard.__*
