---
title: "Week7"
author: "B. Moran"
date: "6 September 2016"
output: 
  pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```
**Due:** 5pm Tuesday 6th September 2016.

If you have any questions about this assignment, please see or email your lecturer for this course, Dr Daniel Sutherland <Daniel.Sutherland@newcastle.edu.au>.

***
test
Questions which review material from Week 5:

1. Consider the operator $T \in L(\mathbb{\mathbb{R}}^{2})$ defined by

$$T (x,y) = (2x + 3y, 4y)$$

(a)	Show that $T$ has an upper-triangular matrix representation with respect to the standard basis $\mathcal{B} = ((1, 0), (0, 1))$ of $\mathbb{\mathbb{R}}^{2}$. Hence state the eigenvalues of $T$.

**Answer:** The matrix representation **A** of $T$ - where it is given that $T$ can be written such that $T = A\vec{x}$ - is:

  $$
    A = 
      \begin{bmatrix}
      2 & 3\\ 0 & 4
      \end{bmatrix}
  $$
  We can reduce $A$ to the standard basis vectors via the following steps:

  $$A =
    \begin{bmatrix} 
    2 & 3\\ 0 & 4 
    \end{bmatrix} 
    \xrightarrow{R^*_2 = R_2*1/4} 
    \begin{bmatrix} 
    2 & 3\\ 0 & 1
    \end{bmatrix} 
    \xrightarrow{R^*_1 = R_1 - 3*R_2} 
    \begin{bmatrix} 
    2 & 0\\ 0 & 1
    \end{bmatrix} 
    \xrightarrow{R^*_1 = R_1 * 1/2} 
    \begin{bmatrix} 
    1 & 0\\ 0 & 1
    \end{bmatrix}.
  $$
  
Now, our original, non-row-reduced matrix **A** was already an upper-triangular matrix. Therefore, we can read the eigenvalues of **A** straight off the main diagonal, which gives us $\lambda_{1} = 2$ and $\lambda_{2} = 4$.

(b)	Show that $T$ also has an upper-triangular matrix representation with respect to the basis $\mathcal{B}' = ((2, 0), (1, 2))$ of $\mathbb{\mathbb{R}}^{2}$. Is this the same matrix you found in part (a)? Should it be?

  $$A =
    \begin{bmatrix} 
    2 & 3\\ 0 & 4 
    \end{bmatrix} 
    \xrightarrow{R^*_2 = R_2 * 1/2} 
    \begin{bmatrix} 
    2 & 3\\ 0 & 2
    \end{bmatrix} 
    \xrightarrow{R^*_1 = R_1 - R_2} 
    \begin{bmatrix} 
    2 & 1\\ 0 & 2
    \end{bmatrix}.
  $$
  
  This is *not* the same matrix that we found in (a), and we know that it shouldn't be; each operator has a unique upper triangular matrix representation *with respect to a particular basis*. Given that we have calculated each matrix with respect to different bases, these representations should not be the same.

  (c)	For any nonzero $k \in \mathbb{R}$, the list of vectors $\mathcal{B}'' = ((1, 0), (1, k))$ is a basis of $\mathbb{\mathbb{R}}^{2}$. Show that $T$ has an upper-triangular matrix representation with respect to the basis $\mathcal{B}''$ (for all nonzero $k \in \mathbb{R})$.
  
    **Answer:** We can reduce $A$ to the basis vectors $\mathcal{B}'' = ((1, 0), (1, k)): k \in \mathbb{R}$ via the following steps:

  $$A =
    \begin{bmatrix} 
    2 & 3\\ 0 & 4 
    \end{bmatrix} 
    \xrightarrow{R^*_2 = R_2*1/4} 
    \begin{bmatrix} 
    2 & 3\\ 0 & 1
    \end{bmatrix} 
    \xrightarrow{R^*_1 = R_1 - R_2} 
    \begin{bmatrix} 
    2 & 2\\ 0 & 1
    \end{bmatrix} 
    \xrightarrow{R^*_1 = R_1 * 1/2} 
    \begin{bmatrix} 
    1 & 1\\ 0 & 1
    \end{bmatrix}
        \xrightarrow{R^*_2 = R_2 * k} 
    \begin{bmatrix} 
    1 & 1\\ 0 & k
    \end{bmatrix}.
  $$

  (d)	For what particular choice of $k$ will $T$ have a diagonal matrix representation? In this case, what does this tell you about the basis vectors in $\mathcal{B}''$?

    **Answer:** $T$ will have a diagonal matrix representation $\forall k \in \mathbb{R}, k \neq 0$.
    
    
2. Consider the operator $T \in L(\mathbb{\mathbb{R}}^{3})$ defined by the matrix multiplication

  $$
    T(x,y,z) = 
      \begin{pmatrix} 
      -1 & 2 & 0 \\ 0 & 0 & 3 \\ 0 & 0 & 0 
      \end{pmatrix}
      \begin{pmatrix}
      x \\ y \\ z 
      \end{pmatrix}
  $$
  


(a)	State the eigenvalues of $T$ , and  find all eigenvectors corresponding to each eigenvalue.

    **Answer:** The matrix $T$ is an upper triangular matrix, so we can read the eigenvalues off the main diagonal: $\lambda_{1} = -1$ with a multiplicty of $1$, and $\lambda_{2} = 0$ with a multiplicity of $2$.
    For $\lambda_{1} = -1$, the corresponding eigenvector is:
    $$
      \begin{bmatrix} 
        0 & 2 & 0 \\ 
        0 & 1 & 3 \\ 
        0 & 0 & 1
      \end{bmatrix} 
      \begin{bmatrix} 
        x_{1} \\
        x_{2} \\
        x_{3}
      \end{bmatrix} 
      =
      \begin{bmatrix} 
        0 \\
        0 \\
        0
      \end{bmatrix}
    $$
There's no pivot variable in the first column of $T$, so the matrix must map all $x_{1}$s into the null space. So the eigenvector for $\lambda_{1} = -1$ is $(1,0,0)$.
For $\lambda_{2} = 0$, we get:
    $$
      \begin{bmatrix} 
        -1 & 2 & 0 \\ 
        0 & 0 & 3 \\ 
        0 & 0 & 0
      \end{bmatrix} 
      \begin{bmatrix} 
        x_{1} \\
        x_{2} \\
        x_{3}
      \end{bmatrix} 
      =
      \begin{bmatrix} 
        0 \\
        0 \\
        0
      \end{bmatrix}
    $$
which implies that $x_{1} = 2x_{2}$. Therefore, the eigenvector for $\lambda_{2} = 0$ is $(2,1,0)$. But, for a $3\times3$ matrix we need another eigenvector, which we'll find in part (b).

(b)	Find all generalised eigenvectors corresponding to each eigenvalue.

    **Answer:** First, let's find $T^{2}$.
    $$
      T^{2}
      =
      \left(
        \begin{bmatrix} 
          -1 & 2 & 0 \\ 
          0 & 0 & 3 \\ 
          0 & 0 & 0
        \end{bmatrix}
      \right)^{2}
      =
      \begin{bmatrix} 
        1 & -2 & 6 \\ 
        0 & 0 & 0 \\ 
        0 & 0 & 0
      \end{bmatrix}
    $$
So $x_{1}$ is our pivot and we have two free variables, $x_{2}$ and $x_{3}$. Setting $x_{2}=1$ and $x_{3}=0$ will return the eigenvector we found in part (a), so let's set $x_{2}=0$ and $x_{3}=1$. This leaves us with the generalised eigenvector for $\lambda_{2} = 0$ as $(-1, 0, 1/6)$. If we rewrite this vector as $(-2, 0, 1/3)$, we can check this is correct by evaluating:
    $$
      \begin{bmatrix} 
        -1 & 2 & 0 \\ 
        0 & 0 & 3 \\ 
        0 & 0 & 0
      \end{bmatrix} 
      \begin{bmatrix} 
        -2 \\
        0 \\
        1/2
      \end{bmatrix} 
      =
      \begin{bmatrix} 
        2 \\
        1 \\
        0
      \end{bmatrix}
    $$  
which is equal to the eigenvector for $\lambda_{2} = 0$ that we found in part (a). Therefore, $(-2, 0, 1/3)$ is a generalised eigenvector for $\lambda_{2} = 0$. Now, the number of eigenvectors we have found is equal to dim(T); therefore there are no more to find.

###Introductory level question relating to Week 6:

3. Consider the operator $T \in \mathcal{L}(\mathbb{C}^{5})$ defined by

$$T(z_{1}, z_{2}, z_{3}, z_{4}, z_{5}) = (0, z_{1}, 0, z_{2}, 0)$$

(a)	Calculate $T^{2}$ and $T^{3}$ applied to $(z_{1}, z_{2}, z_{3}, z_{4}, z_{5})$. Is $T$ nilpotent?

**Answer:** The matrix representation of $T$ is:

  $$
    A = 
      \begin{bmatrix}
      0 & 0 & 0 & 0 & 0 \\ 
      1 & 0 & 0 & 0 & 0 \\ 
      0 & 0 & 0 & 0 & 0 \\ 
      0 & 1 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0
      \end{bmatrix}
  $$

$A^{2}$ equals:
  $$
    A^{2} = 
      \left(\begin{bmatrix}
      0 & 0 & 0 & 0 & 0 \\ 
      1 & 0 & 0 & 0 & 0 \\ 
      0 & 0 & 0 & 0 & 0 \\ 
      0 & 1 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0
      \end{bmatrix}\right)^{2}
      =
      \begin{bmatrix}
      0 & 0 & 0 & 0 & 0 \\ 
      0 & 0 & 0 & 0 & 0 \\ 
      0 & 0 & 0 & 0 & 0 \\ 
      1 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0
      \end{bmatrix}
  $$
and $A^{3}$ equals:
  $$
    A^{3} = 
      \left(\begin{bmatrix}
      0 & 0 & 0 & 0 & 0 \\ 
      1 & 0 & 0 & 0 & 0 \\ 
      0 & 0 & 0 & 0 & 0 \\ 
      0 & 1 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0
      \end{bmatrix}\right)^{3}
      =
      \begin{bmatrix}
      0 & 0 & 0 & 0 & 0 \\ 
      0 & 0 & 0 & 0 & 0 \\ 
      0 & 0 & 0 & 0 & 0 \\ 
      0 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0
      \end{bmatrix}
      =
      \pmb{0}_{5,5}
  $$
Therefore, $T$ is nilpotent.

  (b)	Verify your conclusion by calculating $T^{dim \mathbb{C}^{5}}$.
  
  (c)	You are given that  $\lambda = 0$ is an eigenvalue of $T$ . What are the corresponding eigenvectors?

(d)	Describe the generalised eigenvectors corresponding to $\lambda = 0$.

(e)	Hence state the multiplicity of the eigenvalue $\lambda = 0$ and explain why $T$ cannot have any other eigenvalues.

###Extension question - will not be marked, just for interest!

4.	Can a nilpotent linear operator on a  finite-dimensional vector space be invertible? *Why/why not?*
  
    Can an invertible linear operator on a  nite-dimensional vector space be nilpotent? *Why/why not?*


###Submitting your assignment (due 5pm Tuesday 6th September 2016)

*Submit your assignment in hardcopy in your Demonstrator's pigeonhole in the Assignment boxes near the Maths Clinic, on the opposite wall to the Maths Clinic, left of the door to V109. We also ask that you scan your written work and submit it on the MATH2320 UoNline/Blackboard site as a backup and proof of submission, not as a substitute. __Note that we still require the hardcopy submitted in the Assignment Box for your Demonstrator to mark, even if you have submitted a backup on Blackboard.__*

    
